import { VoicePreset } from '../types';

export const CURATED_VOICE_PRESETS: VoicePreset[] = [
  {
    id: 'studio_narrator',
    title: 'Audiobook Narrator',
    description: 'Warm, expressive, measured cadence with rich emotional depth.',
    icon: 'BookOpen',
    category: 'narrative',
    settings: {
      engine: 'gemini',
      geminiVoice: 'Kore',
      geminiStyle: 'Warm, engaging, gentle cadence, rich storytelling intonation',
      speed: 1.0,
      pitch: 1.0,
      volume: 1.0,
    },
  },
  {
    id: 'broadcast_news',
    title: 'Radio & News Anchor',
    description: 'Crisp articulation, authoritative pace, balanced projection.',
    icon: 'Radio',
    category: 'commercial',
    settings: {
      engine: 'gemini',
      geminiVoice: 'Charon',
      geminiStyle: 'Authoritative, clear, professional news anchor, crisp diction',
      speed: 1.1,
      pitch: 0.95,
      volume: 1.0,
    },
  },
  {
    id: 'podcast_host',
    title: 'Dynamic Podcast Host',
    description: 'Upbeat, friendly, conversational, and energetic.',
    icon: 'Mic2',
    category: 'casual',
    settings: {
      engine: 'gemini',
      geminiVoice: 'Fenrir',
      geminiStyle: 'Enthusiastic, bright podcast host, dynamic, conversational',
      speed: 1.05,
      pitch: 1.0,
      volume: 1.0,
    },
  },
  {
    id: 'meditation_guide',
    title: 'Mindful Sanctuary',
    description: 'Slow, peaceful, breathy, gentle whisper tones for relaxation.',
    icon: 'Sparkles',
    category: 'wellness' as any,
    settings: {
      engine: 'gemini',
      geminiVoice: 'Zephyr',
      geminiStyle: 'Very calm, soothing whisper, slow measured breathing, tranquil',
      speed: 0.85,
      pitch: 0.9,
      volume: 0.9,
    },
  },
  {
    id: 'playful_character',
    title: 'Playful Character',
    description: 'Animated, expressive, youthful with lively pitch variations.',
    icon: 'Smile',
    category: 'creative',
    settings: {
      engine: 'gemini',
      geminiVoice: 'Puck',
      geminiStyle: 'Playful, lively, expressive, curious and animated character',
      speed: 1.1,
      pitch: 1.15,
      volume: 1.0,
    },
  },
  {
    id: 'executive_brief',
    title: 'Executive Briefing',
    description: 'Direct, confident, succinct, perfect for business summaries.',
    icon: 'Briefcase',
    category: 'commercial',
    settings: {
      engine: 'gemini',
      geminiVoice: 'Charon',
      geminiStyle: 'Executive tone, confident, articulate, precise corporate presentation',
      speed: 1.15,
      pitch: 1.0,
      volume: 1.0,
    },
  },
];

export const GEMINI_VOICES_INFO = [
  {
    id: 'Kore',
    name: 'Kore',
    gender: 'female',
    persona: 'Warm Studio Narrator',
    description: 'Natural, expressive, articulate, excellent for audiobooks and narratives.',
    accent: 'Neutral English',
  },
  {
    id: 'Puck',
    name: 'Puck',
    gender: 'male',
    persona: 'Playful & Charismatic',
    description: 'Youthful, energetic, bright intonation for games and creative media.',
    accent: 'Modern English',
  },
  {
    id: 'Charon',
    name: 'Charon',
    gender: 'male',
    persona: 'Deep Cinematic & News',
    description: 'Resonant, authoritative, calm baritone with steady presence.',
    accent: 'Commanding English',
  },
  {
    id: 'Fenrir',
    name: 'Fenrir',
    gender: 'male',
    persona: 'Engaging Podcast Host',
    description: 'Dynamic, confident, enthusiastic delivery for announcements and tutorials.',
    accent: 'Contemporary English',
  },
  {
    id: 'Zephyr',
    name: 'Zephyr',
    gender: 'female',
    persona: 'Smooth & Intelligent AI',
    description: 'Gentle, balanced, crystal-clear timbre for modern digital assistants.',
    accent: 'Polished English',
  },
] as const;

export const STYLE_SUGGESTIONS = [
  'Warm, empathetic, storytelling cadence',
  'Clear, authoritative news anchor',
  'Enthusiastic and upbeat podcast host',
  'Calm, soothing meditation guide with gentle breaths',
  'Crisp, fast-paced technical presenter',
  'Playful and humorous character voice',
  'Dramatic, cinematic movie trailer narrator',
  'Gentle bedtime story reader for children',
];
